// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"context"
	"gogeekbang/internal/dao"
	"gogeekbang/internal/pkg/config"
	"gogeekbang/internal/pkg/db"
	"gogeekbang/internal/pkg/rdb"
	"gogeekbang/internal/service"
)

// Injectors from wire.go:

func InitService(ctx context.Context, databaseConfig config.Database, redisConfig config.Redis) service.Service {
	gormDB := db.NewDB(databaseConfig)
	client := rdb.NewRedis(redisConfig)
	daoDao := dao.NewDao(ctx, gormDB, client)
	serviceService := service.NewService(ctx, daoDao)
	return serviceService
}
